version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234-asdf
      MYSQL_DATABASE: testrestapi
      MYSQL_USER: myuser            # non-root user
      MYSQL_PASSWORD: myuserpass    # password for non-root user
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testrestapi
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: myuserpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  db_data:
